"""Use case: Declares replaceable infrastructure capabilities.

What it does: Defines contracts for queries, models, retrieval, and readiness.
"""

from datetime import datetime
from typing import Any, BinaryIO, Protocol
from uuid import UUID

from execplus.application.contracts import (
    ComponentStatus,
    KnowledgeChunk,
    ModelRequest,
    ModelResponse,
    RetrievalHit,
)
from execplus.application.reporting_ports import ReportingRepository
from execplus.domain.activation import Feedback, ReportDelivery, ReportSchedule
from execplus.domain.analysis_plan import AnalysisPlan
from execplus.domain.forecast_records import ForecastComparison, ForecastRun
from execplus.domain.ingestion import (
    AuditEvent,
    Dataset,
    FileStructure,
    Invitation,
    Membership,
    ObjectMetadata,
    Upload,
    User,
    Workspace,
)
from execplus.domain.jobs import EventStatus, Job, JobAttempt, JobEvent, JobStage
from execplus.domain.join_paths import JoinPath
from execplus.domain.knowledge import Document, DocumentChunk
from execplus.domain.models import QueryExecution, QueryPlan, QueryResult, WorkspaceScope
from execplus.domain.operations import StaffAudit, StaffGrant, SupportEvent, SupportTicket
from execplus.domain.profiling import Revision, TableData, UsageEvent
from execplus.domain.refresh import (
    AlertEvent,
    AlertRule,
    Monitor,
    Observation,
    RefreshCandidate,
    RefreshFeed,
)
from execplus.domain.saved_items import SavedItem
from execplus.domain.semantics import DatasetView
from execplus.domain.studies import (
    Department,
    Organization,
    Study,
    StudyBoard,
    StudyVersion,
    ViewDismissals,
)
from execplus.domain.threads import Thread, ThreadTurn
from execplus.domain.understanding import DataPreference, Understanding


class QueryExecutor(Protocol):
    async def execute(
        self, plan: QueryPlan, scope: WorkspaceScope, table: TableData, view: DatasetView
    ) -> QueryResult: ...

    async def execute_join(
        self,
        plan: QueryPlan,
        scope: WorkspaceScope,
        join_path: JoinPath,
        left_table: TableData,
        left_view: DatasetView,
        right_table: TableData,
        right_view: DatasetView,
    ) -> QueryResult: ...


class LanguageModel(Protocol):
    async def complete(self, request: ModelRequest) -> ModelResponse: ...


class EmbeddingStore(Protocol):
    async def upsert(self, chunks: tuple[KnowledgeChunk, ...]) -> None: ...

    async def search(
        self,
        query: str,
        scope: WorkspaceScope,
        dataset_ids: frozenset[UUID],
        limit: int,
    ) -> tuple[RetrievalHit, ...]: ...

    async def delete_dataset(self, workspace_id: UUID, dataset_id: UUID) -> None: ...


class ReadinessProbe(Protocol):
    @property
    def name(self) -> str: ...

    async def check(self) -> ComponentStatus: ...


class IdentityProvider(Protocol):
    def authenticate(self, token: str) -> "User": ...

    def revoke(self, token: str) -> None: ...


class ObjectStorage(Protocol):
    def put(self, upload: "Upload", content: "BinaryIO") -> None: ...

    def metadata(self, upload: "Upload") -> "ObjectMetadata": ...

    def read(self, upload: "Upload") -> bytes: ...

    def delete(self, upload: "Upload") -> None: ...

    def ready(self) -> bool: ...


class FileParser(Protocol):
    def read_table(self, content: BinaryIO, format: str) -> TableData: ...

    def parse(
        self,
        content: "BinaryIO",
        filename: str,
        content_type: str,
        *,
        stored_format: str | None = None,
    ) -> "FileStructure": ...


class ExecutionProgress(Protocol):
    async def emit(self, stage: JobStage, status: EventStatus) -> None: ...
    async def planned(self, plan: AnalysisPlan) -> None: ...
    async def model_call(self) -> None: ...
    async def provider_attempt(self) -> None: ...


class JobRepository(Protocol):
    def job(self, workspace_id: UUID, job_id: UUID) -> Job: ...
    def add_job(self, job: Job) -> None: ...
    def set_job(self, job: Job) -> None: ...
    def job_candidates(self, now: datetime, limit: int = 100) -> tuple[tuple[UUID, UUID], ...]: ...
    def workspace_job_count(self, workspace_id: UUID, statuses: tuple[str, ...]) -> int: ...
    def add_job_attempt(self, attempt: JobAttempt) -> None: ...
    def job_attempt(self, workspace_id: UUID, job_id: UUID, attempt_id: UUID) -> JobAttempt: ...
    def set_job_attempt(self, attempt: JobAttempt) -> None: ...
    def add_job_event(self, event: JobEvent) -> None: ...
    def job_events(
        self, workspace_id: UUID, job_id: UUID, after: int = 0
    ) -> tuple[JobEvent, ...]: ...


class OperationsRepository(Protocol):
    def staff_grant(self, user_id: UUID, *, lock: bool = False) -> StaffGrant | None: ...
    def set_staff_grant(self, value: StaffGrant) -> None: ...
    def staff_user(self, email: str) -> User: ...
    def active_staff(self) -> tuple[dict[str, Any], ...]: ...
    def add_staff_audit(self, value: StaffAudit) -> None: ...
    def add_support_ticket(self, value: SupportTicket) -> None: ...
    def support_ticket(
        self, workspace_id: UUID, ticket_id: UUID, *, lock: bool = False
    ) -> SupportTicket: ...
    def support_tickets(
        self,
        *,
        workspace_id: UUID | None,
        requester_id: UUID | None,
        before: tuple[datetime, UUID] | None,
        status: str,
        priority: str,
        q: str,
        limit: int,
    ) -> tuple[SupportTicket, ...]: ...
    def support_open_count(self, workspace_id: UUID, requester_id: UUID) -> int: ...
    def set_support_ticket(self, value: SupportTicket, expected_version: int) -> None: ...
    def add_support_event(self, value: SupportEvent) -> None: ...
    def support_events(self, workspace_id: UUID, ticket_id: UUID) -> tuple[SupportEvent, ...]: ...
    def support_feedback_owned(
        self, workspace_id: UUID, feedback_id: UUID, requester_id: UUID
    ) -> bool: ...
    def admin_workspaces(
        self, *, before: tuple[datetime, UUID] | None, q: str, limit: int
    ) -> tuple[dict[str, Any], ...]: ...
    def admin_workspace(self, workspace_id: UUID) -> dict[str, Any]: ...


class WorkspaceRepository(JobRepository, OperationsRepository, ReportingRepository, Protocol):
    def forecast_runs(
        self, workspace_id: UUID, dataset_id: UUID, owner_id: UUID
    ) -> tuple[ForecastRun, ...]: ...
    def forecast_run(self, workspace_id: UUID, record_id: UUID, owner_id: UUID) -> ForecastRun: ...
    def forecast_comparisons(
        self, workspace_id: UUID, forecast_id: UUID, owner_id: UUID
    ) -> tuple[ForecastComparison, ...]: ...
    def forecast_comparison(
        self, workspace_id: UUID, record_id: UUID, owner_id: UUID
    ) -> ForecastComparison: ...

    def refresh_feed(self, workspace_id: UUID, record_id: UUID) -> RefreshFeed: ...
    def refresh_feeds(self, workspace_id: UUID, dataset_id: UUID) -> tuple[RefreshFeed, ...]: ...
    def set_refresh_feed(self, record: RefreshFeed) -> None: ...
    def refresh_candidate(self, workspace_id: UUID, record_id: UUID) -> RefreshCandidate: ...
    def refresh_candidates(
        self, workspace_id: UUID, feed_id: UUID
    ) -> tuple[RefreshCandidate, ...]: ...
    def set_refresh_candidate(self, record: RefreshCandidate) -> None: ...
    def monitor(self, workspace_id: UUID, record_id: UUID) -> Monitor: ...
    def monitors(self, workspace_id: UUID, feed_id: UUID) -> tuple[Monitor, ...]: ...
    def set_monitor(self, record: Monitor) -> None: ...
    def observation(self, workspace_id: UUID, record_id: UUID) -> Observation: ...
    def observations(self, workspace_id: UUID, monitor_id: UUID) -> tuple[Observation, ...]: ...
    def set_observation(self, record: Observation) -> None: ...
    def alert_rule(self, workspace_id: UUID, record_id: UUID) -> AlertRule: ...
    def alert_rules(self, workspace_id: UUID, monitor_id: UUID) -> tuple[AlertRule, ...]: ...
    def set_alert_rule(self, record: AlertRule) -> None: ...
    def alert_event(self, workspace_id: UUID, record_id: UUID) -> AlertEvent: ...
    def alert_events(self, workspace_id: UUID, rule_id: UUID) -> tuple[AlertEvent, ...]: ...
    def set_alert_event(self, record: AlertEvent) -> None: ...
    def due_refreshes(self, now: datetime) -> tuple[tuple[UUID, UUID], ...]: ...
    def pending_observations(
        self, now: datetime, workspace_id: UUID | None = None, dataset_id: UUID | None = None
    ) -> tuple[tuple[UUID, UUID], ...]: ...

    def organizations(self, actor_id: UUID) -> tuple[Organization, ...]: ...
    def organization(self, organization_id: UUID) -> Organization: ...
    def departments(self, organization_id: UUID, actor_id: UUID) -> tuple[Department, ...]: ...
    def set_department(self, department: Department) -> None: ...
    def department(self, workspace_id: UUID) -> Department | None: ...
    def studies(self, workspace_id: UUID, dataset_id: UUID) -> tuple[Study, ...]: ...
    def study(self, workspace_id: UUID, study_id: UUID) -> Study: ...
    def study_versions(self, workspace_id: UUID, study_id: UUID) -> tuple[StudyVersion, ...]: ...
    def study_version(self, workspace_id: UUID, version_id: UUID) -> StudyVersion: ...
    def set_study_shared(self, workspace_id: UUID, study_id: UUID, shared: bool) -> None: ...
    def study_boards(self, workspace_id: UUID) -> tuple[StudyBoard, ...]: ...
    def study_board(self, workspace_id: UUID, board_id: UUID) -> StudyBoard: ...
    def set_study_board(self, board: StudyBoard) -> None: ...
    def view_dismissals(
        self, workspace_id: UUID, dataset_id: UUID, user_id: UUID, understanding_id: UUID
    ) -> list[str]: ...
    def set_view_dismissals(self, dismissals: ViewDismissals) -> None: ...

    def latest_understanding(
        self, workspace_id: UUID, dataset_id: UUID
    ) -> Understanding | None: ...

    def understanding(
        self, workspace_id: UUID, dataset_id: UUID, record_id: UUID
    ) -> Understanding: ...

    def understanding_history(
        self, workspace_id: UUID, dataset_id: UUID
    ) -> tuple[Understanding, ...]: ...

    def data_preference(
        self, workspace_id: UUID, dataset_id: UUID, user_id: UUID
    ) -> DataPreference | None: ...

    def save_data_preference(self, preference: DataPreference) -> None: ...

    def user(self, user_id: UUID) -> "User": ...

    def workspaces(self, user_id: UUID) -> tuple["Workspace", ...]: ...

    def workspace(self, workspace_id: UUID, *, lock: bool = False) -> "Workspace": ...

    def membership(self, workspace_id: UUID, user_id: UUID) -> "Membership": ...

    def members(self, workspace_id: UUID) -> tuple["Membership", ...]: ...

    def invitations(self, workspace_id: UUID) -> tuple["Invitation", ...]: ...

    def invitation(self, workspace_id: UUID, invitation_id: UUID) -> "Invitation": ...

    def set_invitation_status(
        self, workspace_id: UUID, invitation_id: UUID, status: str
    ) -> None: ...

    def remove_member(self, workspace_id: UUID, user_id: UUID) -> None: ...

    def set_seat_limit(self, workspace_id: UUID, limit: int) -> None: ...

    def datasets(self, workspace_id: UUID) -> tuple["Dataset", ...]: ...

    def dataset(self, workspace_id: UUID, dataset_id: UUID) -> "Dataset": ...

    def rename_dataset(self, workspace_id: UUID, dataset_id: UUID, name: str) -> "Dataset": ...

    def uploads(self, workspace_id: UUID, dataset_id: UUID) -> tuple["Upload", ...]: ...

    def upload(self, workspace_id: UUID, dataset_id: UUID, upload_id: UUID) -> "Upload": ...

    def audit_events(self, workspace_id: UUID) -> tuple["AuditEvent", ...]: ...

    def visible_audit_events(
        self,
        workspace_id: UUID,
        actor_id: UUID,
        shared_actions: tuple[str, ...],
        *,
        limit: int | None = None,
        before: tuple[datetime, UUID] | None = None,
        q: str = "",
        action: str = "",
        resource_type: str = "",
        since: datetime | None = None,
        until: datetime | None = None,
    ) -> tuple[AuditEvent, ...]: ...

    def revisions(
        self, workspace_id: UUID, dataset_id: UUID, upload_id: UUID
    ) -> tuple[Revision, ...]: ...

    def revision(
        self, workspace_id: UUID, dataset_id: UUID, upload_id: UUID, revision_id: UUID
    ) -> Revision: ...

    def active_revision(
        self, workspace_id: UUID, dataset_id: UUID, upload_id: UUID
    ) -> Revision | None: ...

    def set_active_revision(self, revision: Revision) -> None: ...

    def usage_events(self, workspace_id: UUID) -> tuple[UsageEvent, ...]: ...

    def query_execution(self, workspace_id: UUID, query_id: UUID) -> QueryExecution: ...

    def set_query_receipt(
        self, workspace_id: UUID, query_id: UUID, receipt: dict[str, object]
    ) -> None: ...

    def saved_items(
        self, workspace_id: UUID, dataset_id: UUID, upload_id: UUID
    ) -> tuple[SavedItem, ...]: ...

    def saved_item(self, workspace_id: UUID, item_id: UUID) -> SavedItem: ...

    def delete_saved_item(self, workspace_id: UUID, item_id: UUID) -> None: ...

    def thread(self, workspace_id: UUID, thread_id: UUID) -> Thread: ...

    def threads(
        self, workspace_id: UUID, dataset_id: UUID, upload_id: UUID, owner_id: UUID
    ) -> tuple[Thread, ...]: ...

    def thread_turns(self, workspace_id: UUID, thread_id: UUID) -> tuple[ThreadTurn, ...]: ...

    def add_thread_turn(self, workspace_id: UUID, turn: ThreadTurn) -> None: ...

    def update_thread_turn(self, workspace_id: UUID, turn: ThreadTurn) -> None: ...

    def join_paths(self, workspace_id: UUID) -> tuple[JoinPath, ...]: ...

    def join_path(self, workspace_id: UUID, join_path_id: UUID) -> JoinPath: ...

    def feedback(self, workspace_id: UUID) -> tuple[Feedback, ...]: ...
    def documents(
        self, workspace_id: UUID, dataset_id: UUID, actor_id: UUID
    ) -> tuple[Document, ...]: ...
    def document(self, workspace_id: UUID, document_id: UUID) -> Document: ...
    def document_chunks(
        self, workspace_id: UUID, document_id: UUID
    ) -> tuple[DocumentChunk, ...]: ...
    def delete_document(self, workspace_id: UUID, document_id: UUID) -> None: ...
    def report_schedules(
        self, workspace_id: UUID, owner_id: UUID
    ) -> tuple[ReportSchedule, ...]: ...
    def report_schedule(self, workspace_id: UUID, schedule_id: UUID) -> ReportSchedule: ...
    def due_schedules(self, now: datetime) -> tuple[tuple[UUID, UUID], ...]: ...
    def set_report_schedule(self, schedule: ReportSchedule) -> None: ...
    def set_report_delivery(self, delivery: ReportDelivery) -> None: ...

    def report_delivery(
        self, workspace_id: UUID, schedule_id: UUID, due_at: datetime
    ) -> ReportDelivery | None: ...

    def add(
        self,
        record: Workspace
        | Membership
        | Invitation
        | Dataset
        | Upload
        | AuditEvent
        | Revision
        | UsageEvent
        | QueryExecution
        | SavedItem
        | Thread
        | ThreadTurn
        | JoinPath
        | Feedback
        | ReportSchedule
        | ReportDelivery
        | Document
        | DocumentChunk
        | Understanding
        | Organization
        | Department
        | Study
        | StudyVersion
        | StudyBoard
        | RefreshFeed
        | RefreshCandidate
        | Monitor
        | Observation
        | AlertRule
        | AlertEvent
        | ForecastRun
        | ForecastComparison,
    ) -> None: ...


class DocumentStorage(Protocol):
    def put_document(self, document: Document, content: bytes) -> None: ...
    def read_document(self, document: Document) -> bytes: ...
    def delete_document(self, document: Document) -> None: ...


class PassageRanker(Protocol):
    def rank(
        self, query: str, chunks: tuple[KnowledgeChunk, ...], limit: int
    ) -> tuple[RetrievalHit, ...]: ...


class EmailDelivery(Protocol):
    def send(self, recipient: str, subject: str, body: str, delivery_id: UUID) -> None: ...
